spring.application.name=alert
# monitoring ms
monitoring.cycle=60000
# kline interval
monitoring.kline.interval=1s,3s
# exclude symbol
monitoring.exclude.symbol=ABC,BBC
# volume usdt low
monitoring.alert.volume.low=200000
# volume usdt high
monitoring.alert.volume.high=4000000
# rate low 0.9%
monitoring.rate.low=0.009

monitoring.rate.back.low=0.03

monitoring.alert.volume.back.low=1000000
# rate high 10%
monitoring.rate.high=0.1


# new
monitoring.rate.two.low=0.01
monitoring.volume.two.low=1000000